### ISSUE TITLE
Share URL for Facebook

### ISSUE THREAD

**Issue by fititnt** [thiamsantos/thiamsantos.github.io#1]
Test:
Share URL "https://thiamsantos.github.io/" on Facebook.  Result:

> 404 - Not Found
> example.com

Problem: wrong `og:url` parameter 

```html
<!DOCTYPE html>
<html lang="en">

  <head>
(...)
  <meta property="og:url" content="https://example.com/page.html">

```

**Comment by thiamsantos** [comment]
Problem [resolved](https://github.com/thiamsantos/thiamsantos.github.io/blob/master/_includes/head.html#L14).

Thanks!!!
